# Generated by Django 4.2.21 on 2025-05-24 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
