# Generated by Django 4.2.21 on 2025-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0003_userprofile_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('store_manager', 'Store Manager')], default='customer', max_length=20),
        ),
    ]
