# Generated by Django 4.2.21 on 2025-05-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0005_rename_issued_on_coupon_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
